services:
  wrapper-manager:
    build: .
    container_name: wrapper-manager
    command: [
      "--host", "0.0.0.0",
      "--port", "9090",
      "--mirror", "false"
    ]
    ports:
      - "8080:8080"
    volumes:
      - data:/root/data
      
volumes:
  data:
